/**
 * Hook that prepares the database for use:
 *   1. Runs any pending Drizzle migrations (creates/updates tables).
 *   2. Seeds default data once the schema is ready, if the DB is empty.
 *
 * Returns { ready, error } so the app can show a loading/error gate before
 * rendering screens that read from the DB.
 */

import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";
import { useEffect, useState } from "react";

import { db } from "./client";
import { seedIfEmpty } from "./seed";
// The generated migrations bundle (drizzle-kit output). Regenerated by
// `npm run db:generate`.
import migrations from "../drizzle/migrations";

export function useDatabase() {
  const { success, error: migrationError } = useMigrations(db, migrations);
  const [seeded, setSeeded] = useState(false);
  const [seedError, setSeedError] = useState<Error | null>(null);

  useEffect(() => {
    if (!success) return;
    let cancelled = false;
    (async () => {
      try {
        await seedIfEmpty(db);
        if (!cancelled) setSeeded(true);
      } catch (e) {
        if (!cancelled) setSeedError(e as Error);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [success]);

  return {
    ready: success && seeded,
    error: migrationError ?? seedError ?? null,
  };
}
