/**
 * Hook that prepares the database for use:
 *   1. Runs any pending Drizzle migrations (creates/updates the tables).
 *   2. Inserts first-run defaults (one wallet + the default category tree) so
 *      the pickers are never empty. Only happens when the DB has no categories.
 *
 * Returns { ready, error } so the app can gate rendering on the DB being ready.
 */

import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";
import { useEffect, useState } from "react";

import { db } from "./client";
import { ensureDefaults } from "./defaults";
// The generated migrations bundle (drizzle-kit output). Regenerated by
// `npm run db:generate`.
import migrations from "../drizzle/migrations";

export function useDatabase() {
  const { success, error: migrationError } = useMigrations(db, migrations);
  const [ready, setReady] = useState(false);
  const [defaultsError, setDefaultsError] = useState<Error | null>(null);

  useEffect(() => {
    if (!success) return;
    let cancelled = false;
    (async () => {
      try {
        await ensureDefaults(db);
        if (!cancelled) setReady(true);
      } catch (e) {
        if (!cancelled) setDefaultsError(e as Error);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [success]);

  return { ready, error: migrationError ?? defaultsError ?? null };
}
