/**
 * Hook that prepares the database for use by running any pending Drizzle
 * migrations (which create/update the tables). The app starts with an empty
 * database; data is added through the app's own UI.
 *
 * Returns { ready, error } so the app can show a loading/error gate before
 * rendering screens that read from the DB.
 */

import { useMigrations } from "drizzle-orm/expo-sqlite/migrator";

import { db } from "./client";
// The generated migrations bundle (drizzle-kit output). Regenerated by
// `npm run db:generate`.
import migrations from "../drizzle/migrations";

export function useDatabase() {
  const { success, error } = useMigrations(db, migrations);
  return { ready: success, error: error ?? null };
}
